name: Build and Attach Artifacts

on:
  push:
    branches: [ "main", "dev" ]

  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]

    runs-on: ${{ matrix.os }}

    env:
      GO_VERSION: "1.23.6"
      CGO_ENABLED: 1

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies
      run: |
        go mod download

    - name: Prepare build variables
      run: |
        BUILD_DIR=${GITHUB_WORKSPACE}/build
        mkdir -p ${BUILD_DIR}

        GOOS=$(go env GOOS)

        if [[ "$GOOS" == "darwin" ]]; then
          GOARCH=amd64
        else
          GOARCH=$(go env GOARCH)
        fi

        ARCHIVE="drt_go_scenario_${GOOS}_${GOARCH}.zip"

        VM_GO_DIR=$(go list -m -f '{{.Dir}}' github.com/TerraDharitri/drt-go-chain-vm)
        VM_GO_DIR_LEGACY=$(go list -m -f '{{.Dir}}' github.com/TerraDharitri/drt-go-chain-vm-v1_4)

        echo "BUILD_DIR=${BUILD_DIR}" >> $GITHUB_ENV
        echo "GOOS=${GOOS}" >> $GITHUB_ENV
        echo "GOARCH=${GOARCH}" >> $GITHUB_ENV
        echo "ARCHIVE=${ARCHIVE}" >> $GITHUB_ENV
        echo "VM_GO_DIR=${VM_GO_DIR}" >> $GITHUB_ENV
        echo "VM_GO_DIR_LEGACY=${VM_GO_DIR_LEGACY}" >> $GITHUB_ENV

    - name: Build binary
      run: |
        cd cmd/drt-go-scenario
        GOOS=$GOOS GOARCH=$GOARCH go build -o "${BUILD_DIR}/drt-go-scenario"

    - name: Link Wasmer libraries
      run: |

        if [[ "$GOOS" == "linux" ]]; then

          cp ${VM_GO_DIR}/wasmer2/libvmexeccapi.so ${BUILD_DIR}/
          cp ${VM_GO_DIR_LEGACY}/wasmer/libwasmer_linux_amd64.so ${BUILD_DIR}/

          patchelf --replace-needed libvmexeccapi.so libvmexeccapi.so ${BUILD_DIR}/drt-go-scenario
          patchelf --replace-needed libwasmer_linux_amd64.so libwasmer_linux_amd64.so ${BUILD_DIR}/drt-go-scenario
          patchelf --set-rpath "\$ORIGIN" ${BUILD_DIR}/drt-go-scenario

          ldd ${BUILD_DIR}/drt-go-scenario

        fi


        if [[ "$GOOS" == "darwin" ]]; then

          cp ${VM_GO_DIR}/wasmer2/libvmexeccapi.dylib ${BUILD_DIR}/
          cp ${VM_GO_DIR_LEGACY}/wasmer/libwasmer_darwin_amd64.dylib ${BUILD_DIR}/

          install_name_tool -id "@rpath/libvmexeccapi.dylib" ${BUILD_DIR}/libvmexeccapi.dylib
          install_name_tool -id "@rpath/libwasmer_darwin_amd64.dylib" ${BUILD_DIR}/libwasmer_darwin_amd64.dylib
          install_name_tool -add_rpath "@loader_path" ${BUILD_DIR}/drt-go-scenario

          otool -L ${BUILD_DIR}/drt-go-scenario

        fi

    - name: Smoke test
      run: |
        sudo rm -rf ${GOPATH}/pkg/mod

        cd ${BUILD_DIR}
        ./drt-go-scenario --version

        cd ${GITHUB_WORKSPACE}
        ${BUILD_DIR}/drt-go-scenario --version

    - name: Package binary
      run: |
        cd ${BUILD_DIR}
        zip -r ${ARCHIVE} *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: drt-build-${{ matrix.os }}
        path: build/${{ env.ARCHIVE }}

    - name: Upload to release
      if: github.event_name == 'release'
      run: |
        gh release upload ${{ github.event.release.tag_name }} build/${ARCHIVE}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}